[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
target-version = ["py38", "py39", "py310"]
extend-exclude = '__pycache__'
line-length = 140

# Docs: https://gitlab.com/mbarkhau/pycalver
[bumpver]
current_version = "0.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "[bumpver] {new_version}"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"README.md"  = [
    "{version}"
]
"VERSION" = ["{version}"]
"pyproject.toml" = ['current_version = "{version}"']
