# Generated by Django 4.1.4 on 2023-02-04 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="historicalalert",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
