name: Django Tests in user_watch_management

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    paths:
      - 'user_watch_management/**'

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        cd user_watch_management
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Set up Database
      run: |
        cd user_watch_management
        python manage.py migrate

    - name: Run Django tests
      run: |
        cd user_watch_management
        python manage.py test
